- name: Install Jenkins and Docker and cloude watch
  hosts: jenkins
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update
      
    - name: Install Java
      apt:
        name: default-jre
        state: present
        
    - name: Add Jenkins repository key
      apt_key:
         url: https://pkg.jenkins.io/debian/jenkins.io.key
         state: present
         
    - name: Add Jenkins repository
      apt_repository:
          repo: deb http://pkg.jenkins.io/debian-stable binary/
          state: present
          
    - name: Install Jenkins
      apt:
       name: jenkins
       state: present
       
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
        
    - name: Install required system packages for Docker
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common'] 
        state: present
        
    - name: Add Docker GPG key
       apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
       
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        
    - name: Add ansible user to the docker group
      user:
         name: ansible
         groups: docker
         append: yes
         
    - name: Download the CloudWatch agent installer
      get_url:
            url: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
            dest: /tmp/AmazonCloudWatchAgent.zip
            
    - name: Install unzip package
      package:
         name: unzip
         state: present
         
    - name: Unzip the CloudWatch agent installer
      unarchive:
         src: /tmp/AmazonCloudWatchAgent.zip
         dest: /tmp/
         remote_src: yes
      
    - name: Install the CloudWatch agent
      shell: |
             cd /tmp
             ./install.sh
      register: install_result
      changed_when: '"Successfully installed the CloudWatch Agent" in install_result.stdout'
      
    - name: Start the CloudWatch agent
      service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes 
    
    - name: Download kubectl binary
      get_url:
         url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         dest: /tmp/kubectl
         mode: 0755
    
    - name: Download kubectl checksum
      get_url:
         url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
         dest: /tmp/kubectl.sha256
         mode: 0644
    
    - name: Verify kubectl binary
      shell: |
             echo "$(cat /tmp/kubectl.sha256)  /tmp/kubectl" | sha256sum --check
      register: kubectl_checksum
    
    - name: Install kubectl
      become: true
      copy:
         src: /tmp/kubectl
         dest: /usr/local/bin/kubectl
         mode: 0755
      when: kubectl_checksum.rc == 0
    
    - name: Verify kubectl version
      command: kubectl version --client
      register: kubectl_version
      changed_when: false
    
    - debug:
         msg: "kubectl version: {{ kubectl_version.stdout }}"
    
